server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: always
logging:
  level:
    root: info

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true