DROP TABLE IF EXISTS author;
CREATE TABLE author
(
    id   BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS genre;
CREATE TABLE genre
(
    id   BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS book;
CREATE TABLE book
(
    id        BIGINT PRIMARY KEY AUTO_INCREMENT,
    name      VARCHAR(50) NOT NULL,
    author_id BIGINT,
    genre_id  BIGINT,
    FOREIGN KEY (author_id) REFERENCES author (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genre (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS comment;
CREATE TABLE comment
(
    id      BIGINT PRIMARY KEY AUTO_INCREMENT,
    text    TEXT NOT NULL,
    book_id BIGINT,
    FOREIGN KEY (book_id) REFERENCES book (id)
    ON UPDATE CASCADE ON DELETE CASCADE
)